// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNBHvIR2CFOTrMneyQpqeW1xXX6fj4as',
    appId: '1:258461153372:web:e75561a6ce797026914e99',
    messagingSenderId: '258461153372',
    projectId: 'todo-firebase-ad767',
    authDomain: 'todo-firebase-ad767.firebaseapp.com',
    storageBucket: 'todo-firebase-ad767.appspot.com',
    measurementId: 'G-XFXX4N2S15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMI9wEdWo73pilKoP9cgTHyBsnW5OoJ4',
    appId: '1:258461153372:android:e3b5cca722a0b1fd914e99',
    messagingSenderId: '258461153372',
    projectId: 'todo-firebase-ad767',
    storageBucket: 'todo-firebase-ad767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOkcCL7MteVSBUlWPVDAjmrZmPj1WyQc',
    appId: '1:258461153372:ios:d2f0b88b85cf179d914e99',
    messagingSenderId: '258461153372',
    projectId: 'todo-firebase-ad767',
    storageBucket: 'todo-firebase-ad767.appspot.com',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOkcCL7MteVSBUlWPVDAjmrZmPj1WyQc',
    appId: '1:258461153372:ios:29e8a9ebd238e67c914e99',
    messagingSenderId: '258461153372',
    projectId: 'todo-firebase-ad767',
    storageBucket: 'todo-firebase-ad767.appspot.com',
    iosBundleId: 'com.example.firebaseTodo.RunnerTests',
  );
}
